### ISSUE TITLE
Where has the Deep Learning model been deployed?

### ISSUE THREAD

**Issue by Tixierae** [dfalbel/shiny-quora-question-pairs#1]
Hi @jjallaire I'm really interested in knowing what service you are using to host the Deep Learning model trained [here](https://blogs.rstudio.com/tensorflow/posts/2018-01-09-keras-duplicate-questions-quora/) and exposed in this app: https://jjallaire.shinyapps.io/shiny-quora/

Is the model loaded directly in the app (which is possible since shinyapps.io supports Python and tensorflow)? Or does the app call a [Google global prediction platform API](https://cloud.google.com/ml-engine/) as suggested [here](https://tensorflow.rstudio.com/tools/cloudml/articles/getting_started.html) or an [Heroku](https://cloud.google.com/ml-engine/) API? Or anything else?

Also, more generally, do you have any advice on what solution is best to expose Deep Learning models trained with keras/TensorFlow as APIs?

**Comment by dfalbel** [comment]
@Tixierae Hi!
The app is hosted on shinyapps.io and is loaded directly in the app. 

[Here](https://github.com/dfalbel/shiny-quora-question-pairs/blob/master/quora_question_pairs.Rmd) is the complete code for the app.

The best solution to make predictions in large scale is tensorflow serving. However for simple models you can also serve it in a plumber API.

There's an article about deploying tensorflow models [here](https://tensorflow.rstudio.com/tools/tfdeploy/articles/introduction.html).

**Comment by Tixierae** [comment]
Thank you very much for the information. I've been deploying shiny apps on shinyapps.io that load models with keras and tensorflow too. However, although the models weights are not very big (4 models at 6MB each) and the models are loaded only on the user's request once the app has started, I've been experiencing issues on startup. The instances allocated to the app take 30 seconds or so until they are ready to serve the app, and in the meantime a 503 error screen shows. Maybe this has to do with the tensorflow environment.

But when I tested your app, it started almost immediately, that's why I was wondering, maybe the DL model is hosted somewhere else.

**Comment by dfalbel** [comment]
I think this is not expected. Can you tell me if you have this issue happens when you host this app too? Or send me an example where this happens so I can take a look?

**Comment by Tixierae** [comment]
Thank you for your interest. I never tried to host the app on any of my machines. I just run it locally, that's all (without any issue). I use shinyapps.io for deployment. I have filed a detailed issue on RStudio support (see bottom of the thread): https://support.rstudio.com/hc/en-us/requests/35035
You might need an RStudio account to see the thread, though
